GET http://localhost/api/user/me
Content-Type: application/json
Accept-Language: uz
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJiNDY5YWIxNS05MzlkLTRhYWYtYTllNy04ZjQ4ZjViNWYyYjciLCJpYXQiOjE2MjM5MjAwOTMsImV4cCI6MTYyNTY0ODA5Mywicm9sZXMiOlt7ImlkIjoxLCJyb2xlTmFtZSI6IlJPTEVfU1VQRVJfQURNSU4iLCJhdXRob3JpdHkiOiJST0xFX1NVUEVSX0FETUlOIn1dfQ.Cb2g8GnOGB7oqQ014rJGyxS7PvVnvEUhfe6uIdzdByiIJ6PZfdgQgPlWTmdGL5i2RTmR8OLNw9ufUCOOFZvi6w

###

POST http://localhost/api/auth/login
Content-Type: application/json
Accept-Language: uz

{
  "phoneNumber": "+998977117711",
  "password": "root123"
}

###

POST http://localhost:8030/api/auth/login
Content-Type: application/json
Accept-Language: uz
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzYmI0ZGJjYS0yY2U3LTQwMDMtYjY0ZC1kNWMzOWFkNmVhMmQiLCJpYXQiOjE2MjI1NzU2MjIsImV4cCI6MTYyMzE4MDQyMiwicm9sZXMiOlt7ImlkIjoxLCJyb2xlTmFtZSI6IlJPTEVfU1VQRVJfQURNSU4iLCJhdXRob3JpdHkiOiJST0xFX1NVUEVSX0FETUlOIn1dfQ.cXbn_6Czmkzy9hr2YEs77KAullWLsUOmUL1OELkCxBvEguPDkGMV1BAmVgaKHGMJXgcrITAWZf8EOF9F9ovL2g

{
  "phoneNumber": "+998992344565",
  "password": "root123"
}

###

POST http://localhost:8070/api/auth/register
Content-Type: application/json
Accept-Language: uz

{
  "firstName": "Client",
  "lastName": "Clientova",
  "surName": "Clientovna",
  "userName": "client_clientova",
  "phoneNumber": "+998977111923",
  "email": "clientxon123@gmail.com"
}
###

PUT http://localhost:8070/api/user/editPassword
Content-Type: application/json
#Accept-Language: uz
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI3NTMxMWY5Zi05ZGQxLTQ2MzctYWYyMC1lMTk1NGFiMWIzYTIiLCJpYXQiOjE2MjM1NjU5NzMsImV4cCI6MTYyNTI5Mzk3Mywicm9sZXMiOlt7ImlkIjoyLCJyb2xlTmFtZSI6IlJPTEVfQ0xJRU5UIiwiYXV0aG9yaXR5IjoiUk9MRV9DTElFTlQifV19.lJNOHPiPnQlkb1CHskHaFoWpa1Wosrj9Gkvgx4JIDNuXWQPZT6ivJiT3aJ1BUjmrdceh954X5Xlf_IuTYigFaw

{
  "password": "root123"
}
